package com.shushu.utils;

public class MailTemplate {
	public static String registtmp(String username, String code) {

		String str = "<div id=\"contentDiv\" onmouseover=\"getTop().stopPropagation(event);\" onclick=\"getTop().preSwapLink(event, 'spam', 'ZC3519-D54UTDHKbF2CTh1KT_oHB69');\" style=\"position:relative;font-size:14px;height:auto;padding:15px 15px 10px 15px;z-index:1;zoom:1;line-height:1.7;\" class=\"body\">    <div id=\"qm_con_body\"><div id=\"mailContentContainer\" class=\"qmbox qm_con_body_content qqmail_webmail_only\">\n"
				+ "    <style type=\"text/css\" media=\"screen\">\n"
				+ "        .qmbox td,.qmbox\n"
				+ "        h1,.qmbox\n"
				+ "        h2,.qmbox\n"
				+ "        h3 {\n"
				+ "            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\n"
				+ "        }\n"
				+ "        .qmbox _media screen and (min-width: 600px) {\n"
				+ "        .qmbox .main,.qmbox\n"
				+ "        .banner,.qmbox\n"
				+ "        .unsubscribe {\n"
				+ "            width: 600px !important;\n"
				+ "            margin: 0 auto !important;\n"
				+ "        }\n"
				+ "        .qmbox .banner-wrapper {\n"
				+ "            padding-top: 35px !important;\n"
				+ "        }\n"
				+ "        .qmbox .inner {\n"
				+ "            padding: 40px 50px 35px 50px !important;\n"
				+ "        }\n"
				+ "        .qmbox h1 {\n"
				+ "            font-size: 24px !important;\n"
				+ "            line-height: 34px !important;\n"
				+ "            font-weight: 700 !important;\n"
				+ "        }\n"
				+ "        .qmbox h2 {\n"
				+ "            font-size: 14px !important;\n"
				+ "        }\n"
				+ "        .qmbox h3 {\n"
				+ "            font-size: 18px !important;\n"
				+ "        }\n"
				+ "        .qmbox .streak-cell {\n"
				+ "            padding: 3 0px 40px !important;\n"
				+ "        }\n"
				+ "        .qmbox .break {\n"
				+ "            padding-bottom: 30px !important;\n"
				+ "            line-height: 30px !important;\n"
				+ "        }\n"
				+ "        .qmbox .progress-length {\n"
				+ "            width: 200px !important;\n"
				+ "        }\n"
				+ "        .qmbox .skill-icon {\n"
				+ "            padding: 35px 0 !important;\n"
				+ "        }\n"
				+ "        .qmbox .wb-ftr {\n"
				+ "            width: 8px !important;\n"
				+ "        }\n"
				+ "        .qmbox .wc-ftr {\n"
				+ "            width: 14px !important;\n"
				+ "        }\n"
				+ "        .qmbox .share-btn {\n"
				+ "            height: 38px !important;\n"
				+ "            line-height: 36px !important;\n"
				+ "        }\n"
				+ "        .qmbox .tw-follow {\n"
				+ "            padding-right: 7px !important;\n"
				+ "            display: table-cell !important;\n"
				+ "        }\n"
				+ "        .qmbox .fb-follow {\n"
				+ "            padding-left: 7px !important;\n"
				+ "            display: table-cell !important;\n"
				+ "        }\n"
				+ "        .qmbox .share-link {\n"
				+ "            padding: 5px 0 !important;\n"
				+ "        }\n"
				+ "        .qmbox .gray-border {\n"
				+ "            height: 38px !important;\n"
				+ "            width: 19px !important;\n"
				+ "        }\n"
				+ "        .qmbox .social-ftr {\n"
				+ "            height: 36px !important;\n"
				+ "            line-height: 36px !important;\n"
				+ "        }\n"
				+ "        .qmbox .wb-follow-inner,.qmbox\n"
				+ "        .wc-follow-inner {\n"
				+ "            height: 26px !important;\n"
				+ "            line-height: 26px !important;\n"
				+ "        }\n"
				+ "        .qmbox .wc-follow-inner {\n"
				+ "            margin-left: auto !important;\n"
				+ "        }\n"
				+ "        .qmbox .wb-follow-inner {\n"
				+ "            margin-right: auto !important;\n"
				+ "        }\n"
				+ "        .qmbox .follow-link {\n"
				+ "            line-height: 35px !important;\n"
				+ "            padding: 10px 0 !important;\n"
				+ "            font-size: 12px !important;\n"
				+ "        }\n"
				+ "        }\n"
				+ "\n"
				+ "        .qmbox _media only screen and (max-device-width: 600px) {\n"
				+ "        .qmbox .main {\n"
				+ "            width: 100% !important;\n"
				+ "            max-width: 600px !important;\n"
				+ "        }\n"
				+ "        }\n"
				+ "\n"
				+ "        .qmbox _media only screen and (min-device-width: 4800px) and (max-device-width: 600px) {\n"
				+ "        .qmbox .main {\n"
				+ "            width: 100% !important;\n"
				+ "            max-width: 600px !important;\n"
				+ "        }\n"
				+ "        }\n"
				+ "    </style>\n"
				+ "\n"
				+ "\n"
				+ "\n"
				+ "    <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" bgcolor=\"#f3f3f3\" style=\"color: #4A4A4A; font-family: 'Museo Sans Rounded', Museo Sans Rounded, 'Museo Sans', Museo Sans, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; border-collapse: callapse; border-spacing: 0; margin: 0 auto\">\n"
				+ "        <tbody>\n"
				+ "        <tr>\n"
				+ "\n"
				+ "            <td style=\"padding-left: 10px; padding-right: 10px\">\n"
				+ "                <table class=\"main\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" width=\"100%\" style=\"width:100%; margin:0 auto; max-width: 600px\">\n"
				+ "                    <tbody>\n"
				+ "                    <tr>\n"
				+ "                        <td class=\"banner-wrapper\" style=\"text-align: center; padding-top: 3%;\">\n"
				+ "                            <a href=\"http://www.jisuanke.com/?from_email\" target=\"_blank\" style=\"text-decoration: none;\">\n"
				+ "                            </a>\n"
				+ "                        </td>\n"
				+ "                    </tr>\n"
				+ "\n"
				+ "                    <tr>\n"
				+ "                        <td class=\"inner\" bgcolor=\"#ffffff\" style=\"background-color: #ffffff; padding: 9%;\">\n"
				+ "                            <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"width: 100%; padding-bottom: 20px\">\n"
				+ "                                <tbody>\n"
				+ "                                <tr>\n"
				+ "                                    <td width=\"100%\">\n"
				+ "                                        <h1 style=\"font-size: 18px; font-weight: 700; color: #404040; line-height: 24px; margin: 0 0 15px 0;\">\n"
				+ "                                            欢迎加入“Fileware”的大家庭\n"
				+ "                                        </h1>\n"
				+ "                                        <p style=\"color: #888; font-size: 15px; font-weight: normal; line-height: 24px; margin: 0 0 15px 0;\">\n"
				+ "                                            亲爱的 <strong><span style=\"border-bottom: 1px dashed rgb(204, 204, 204); z-index: 1; position: static;\" t=\"7\" onclick=\"return false;\" data=\""
				+ "\">"
				+ username
				+ "</span></strong>:\n"
				+ "                                        </p>\n"
				+ "                                        <p style=\"color: #888; font-size: 15px; font-weight: normal; line-height: 24px; margin: 0;\">\n"
				+ "                                            欢迎您加入Fileware的大家庭，Fileware是一个帮助你更好分类整理文件，分享文件，管理文件的系统，如果您发现任何问题，请向lyshushu1234@gmail.com反馈。\n"
				+ "                                        </p>\n"
				+ "                                    </td>\n"
				+ "                                </tr>\n"
				+ "                                </tbody>\n"
				+ "                            </table>\n"
				+ "\n"
				+ "                            <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"width: 100%;\">\n"
				+ "                                <tbody>\n"
				+ "                                <tr>\n"
				+ "                                    <td class=\"goal\" style=\"background-color:#FFFFFF;\">\n"
				+ "                                        <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"width: 100%;\">\n"
				+ "                                            <tbody>\n"
				+ "                                            <tr>\n"
				+ "                                                <td class=\"skill-icon\" style=\"padding: 10px 0 10px 0;\">\n"
				+ "                                                </td>\n"
				+ "                                            </tr>\n"
				+ "                                            <tr>\n"
				+ "                                                <td style=\"padding: 10px 0\" align=\"center\">\n"
				+ "                                                    <table dir=\"ltr\" class=\"action-btn\" border=\"0\" borderspacing=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"line-height: 22px; margin: 0 auto; height: 34px;\">\n"
				+ "                                                        <tbody>\n"
				+ "                                                        <tr>\n"
				+ "\n"
				+ "                                                            <td borderspacing=\"0\" valign=\"middle\" height=\"38\" style=\"-webkit-text-size-adjust: none; background-color: #4ABA4F; font-size: 14px\">\n"
				+ "                                                                <a class=\"action-btn-middle\" style=\"color: #ffffff; font-weight: 700; text-decoration: none; font-size: 14px !important; padding-top:10px; padding-bottom:10px\" href=\""
				+ "http://localhost:8080/filedata2/user_active.action?code="
				+ code
				+ "\" target=\"_blank\">点击这里激活账号</a>\n"
				+ "                                                            </td>\n"
				+ "\n"
				+ "                                                        </tr>\n"
				+ "                                                        </tbody>\n"
				+ "                                                    </table>\n"
				+ "                                                </td>\n"
				+ "                                            </tr>\n"
				+ "                                            </tbody>\n"
				+ "                                        </table>\n"
				+ "                                    </td>\n"
				+ "                                </tr>\n"
				+ "                                </tbody>\n"
				+ "                            </table>\n"
				+ "                        </td>\n"
				+ "                    </tr>\n"
				+ "\n"
				+ "                    <tr>\n"
				+ "                        <td border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"padding: 20px 0;\">\n"
				+ "                            <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" align=\"center\" style=\"color: #808080; font-size: 14px; line-height: 18px; border-collapse: collapse;\">\n"
				+ "\n"
				+ "                            </table>\n"
				+ "                            <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"border-collapse: collapse;\">\n"
				+ "                                <tbody>\n"
				+ "                                <tr>\n"
				+ "                                    <td class=\"unsubscribe\" width=\"100%\" style=\"padding: 20px\">\n"
				+ "                                        <div style=\"margin: 0; font-size: 11px; text-align: center; color: #BBBBBB;  -webkit-text-size-adjust:none;\">© 2017 Fileware</div>\n"
				+ "                                    </td>\n"
				+ "                                </tr>\n"
				+ "                                </tbody>\n"
				+ "                            </table>\n"
				+ "                        </td>\n"
				+ "                    </tr>\n"
				+ "                    </tbody>\n"
				+ "                </table>\n"
				+ "            </td>\n"
				+ "        </tr>\n"
				+ "        </tbody>\n"
				+ "    </table>\n"
				+ "    <br><br><div style=\"width:1px;height:0px;overflow:hidden\"></div>\n"
				+ "\n"
				+ "    <style type=\"text/css\">.qmbox style, .qmbox script, .qmbox head, .qmbox link, .qmbox meta {display: none !important;}</style></div></div><!-- --><style>#mailContentContainer .txt {height:auto;}</style>  </div>\n";

		return str;
	}

	public static String resetpwdtmp(String username, String id) {

		String str = "<div id=\"contentDiv\" onmouseover=\"getTop().stopPropagation(event);\" onclick=\"getTop().preSwapLink(event, 'spam', 'ZC3519-D54UTDHKbF2CTh1KT_oHB69');\" style=\"position:relative;font-size:14px;height:auto;padding:15px 15px 10px 15px;z-index:1;zoom:1;line-height:1.7;\" class=\"body\">    <div id=\"qm_con_body\"><div id=\"mailContentContainer\" class=\"qmbox qm_con_body_content qqmail_webmail_only\">\n"
				+ "    <style type=\"text/css\" media=\"screen\">\n"
				+ "        .qmbox td,.qmbox\n"
				+ "        h1,.qmbox\n"
				+ "        h2,.qmbox\n"
				+ "        h3 {\n"
				+ "            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\n"
				+ "        }\n"
				+ "        .qmbox _media screen and (min-width: 600px) {\n"
				+ "        .qmbox .main,.qmbox\n"
				+ "        .banner,.qmbox\n"
				+ "        .unsubscribe {\n"
				+ "            width: 600px !important;\n"
				+ "            margin: 0 auto !important;\n"
				+ "        }\n"
				+ "        .qmbox .banner-wrapper {\n"
				+ "            padding-top: 35px !important;\n"
				+ "        }\n"
				+ "        .qmbox .inner {\n"
				+ "            padding: 40px 50px 35px 50px !important;\n"
				+ "        }\n"
				+ "        .qmbox h1 {\n"
				+ "            font-size: 24px !important;\n"
				+ "            line-height: 34px !important;\n"
				+ "            font-weight: 700 !important;\n"
				+ "        }\n"
				+ "        .qmbox h2 {\n"
				+ "            font-size: 14px !important;\n"
				+ "        }\n"
				+ "        .qmbox h3 {\n"
				+ "            font-size: 18px !important;\n"
				+ "        }\n"
				+ "        .qmbox .streak-cell {\n"
				+ "            padding: 3 0px 40px !important;\n"
				+ "        }\n"
				+ "        .qmbox .break {\n"
				+ "            padding-bottom: 30px !important;\n"
				+ "            line-height: 30px !important;\n"
				+ "        }\n"
				+ "        .qmbox .progress-length {\n"
				+ "            width: 200px !important;\n"
				+ "        }\n"
				+ "        .qmbox .skill-icon {\n"
				+ "            padding: 35px 0 !important;\n"
				+ "        }\n"
				+ "        .qmbox .wb-ftr {\n"
				+ "            width: 8px !important;\n"
				+ "        }\n"
				+ "        .qmbox .wc-ftr {\n"
				+ "            width: 14px !important;\n"
				+ "        }\n"
				+ "        .qmbox .share-btn {\n"
				+ "            height: 38px !important;\n"
				+ "            line-height: 36px !important;\n"
				+ "        }\n"
				+ "        .qmbox .tw-follow {\n"
				+ "            padding-right: 7px !important;\n"
				+ "            display: table-cell !important;\n"
				+ "        }\n"
				+ "        .qmbox .fb-follow {\n"
				+ "            padding-left: 7px !important;\n"
				+ "            display: table-cell !important;\n"
				+ "        }\n"
				+ "        .qmbox .share-link {\n"
				+ "            padding: 5px 0 !important;\n"
				+ "        }\n"
				+ "        .qmbox .gray-border {\n"
				+ "            height: 38px !important;\n"
				+ "            width: 19px !important;\n"
				+ "        }\n"
				+ "        .qmbox .social-ftr {\n"
				+ "            height: 36px !important;\n"
				+ "            line-height: 36px !important;\n"
				+ "        }\n"
				+ "        .qmbox .wb-follow-inner,.qmbox\n"
				+ "        .wc-follow-inner {\n"
				+ "            height: 26px !important;\n"
				+ "            line-height: 26px !important;\n"
				+ "        }\n"
				+ "        .qmbox .wc-follow-inner {\n"
				+ "            margin-left: auto !important;\n"
				+ "        }\n"
				+ "        .qmbox .wb-follow-inner {\n"
				+ "            margin-right: auto !important;\n"
				+ "        }\n"
				+ "        .qmbox .follow-link {\n"
				+ "            line-height: 35px !important;\n"
				+ "            padding: 10px 0 !important;\n"
				+ "            font-size: 12px !important;\n"
				+ "        }\n"
				+ "        }\n"
				+ "\n"
				+ "        .qmbox _media only screen and (max-device-width: 600px) {\n"
				+ "        .qmbox .main {\n"
				+ "            width: 100% !important;\n"
				+ "            max-width: 600px !important;\n"
				+ "        }\n"
				+ "        }\n"
				+ "\n"
				+ "        .qmbox _media only screen and (min-device-width: 4800px) and (max-device-width: 600px) {\n"
				+ "        .qmbox .main {\n"
				+ "            width: 100% !important;\n"
				+ "            max-width: 600px !important;\n"
				+ "        }\n"
				+ "        }\n"
				+ "    </style>\n"
				+ "\n"
				+ "\n"
				+ "\n"
				+ "    <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" bgcolor=\"#f3f3f3\" style=\"color: #4A4A4A; font-family: 'Museo Sans Rounded', Museo Sans Rounded, 'Museo Sans', Museo Sans, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; border-collapse: callapse; border-spacing: 0; margin: 0 auto\">\n"
				+ "        <tbody>\n"
				+ "        <tr>\n"
				+ "\n"
				+ "            <td style=\"padding-left: 10px; padding-right: 10px\">\n"
				+ "                <table class=\"main\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" width=\"100%\" style=\"width:100%; margin:0 auto; max-width: 600px\">\n"
				+ "                    <tbody>\n"
				+ "                    <tr>\n"
				+ "                        <td class=\"banner-wrapper\" style=\"text-align: center; padding-top: 3%;\">\n"
				+ "                            <a href=\"http://www.jisuanke.com/?from_email\" target=\"_blank\" style=\"text-decoration: none;\">\n"
				+ "                            </a>\n"
				+ "                        </td>\n"
				+ "                    </tr>\n"
				+ "\n"
				+ "                    <tr>\n"
				+ "                        <td class=\"inner\" bgcolor=\"#ffffff\" style=\"background-color: #ffffff; padding: 9%;\">\n"
				+ "                            <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"width: 100%; padding-bottom: 20px\">\n"
				+ "                                <tbody>\n"
				+ "                                <tr>\n"
				+ "                                    <td width=\"100%\">\n"
				+ "                                        <h1 style=\"font-size: 18px; font-weight: 700; color: #404040; line-height: 24px; margin: 0 0 15px 0;\">\n"
				+ "                                            “Fileware”用户密码重置\n"
				+ "                                        </h1>\n"
				+ "                                        <p style=\"color: #888; font-size: 15px; font-weight: normal; line-height: 24px; margin: 0 0 15px 0;\">\n"
				+ "                                            亲爱的 <strong><span style=\"border-bottom: 1px dashed rgb(204, 204, 204); z-index: 1; position: static;\" t=\"7\" onclick=\"return false;\" data=\""
				+ "\">"
				+ username
				+ "</span></strong>:\n"
				+ "                                        </p>\n"
				+ "                                        <p style=\"color: #888; font-size: 15px; font-weight: normal; line-height: 24px; margin: 0;\">\n"
				+ "                                            Fileware是一个帮助你更好分类整理文件，分享文件，管理文件的系统，如果您发现任何问题，请向lyshushu1234@gmail.com反馈。\n"
				+ "                                        </p>\n"
				+ "                                    </td>\n"
				+ "                                </tr>\n"
				+ "                                </tbody>\n"
				+ "                            </table>\n"
				+ "\n"
				+ "                            <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"width: 100%;\">\n"
				+ "                                <tbody>\n"
				+ "                                <tr>\n"
				+ "                                    <td class=\"goal\" style=\"background-color:#FFFFFF;\">\n"
				+ "                                        <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"width: 100%;\">\n"
				+ "                                            <tbody>\n"
				+ "                                            <tr>\n"
				+ "                                                <td class=\"skill-icon\" style=\"padding: 10px 0 10px 0;\">\n"
				+ "                                                </td>\n"
				+ "                                            </tr>\n"
				+ "                                            <tr>\n"
				+ "                                                <td style=\"padding: 10px 0\" align=\"center\">\n"
				+ "                                                    <table dir=\"ltr\" class=\"action-btn\" border=\"0\" borderspacing=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"line-height: 22px; margin: 0 auto; height: 34px;\">\n"
				+ "                                                        <tbody>\n"
				+ "                                                        <tr>\n"
				+ "\n"
				+ "                                                            <td borderspacing=\"0\" valign=\"middle\" height=\"38\" style=\"-webkit-text-size-adjust: none; background-color: #de2121; font-size: 14px\">\n"
				+ "                                                                <a class=\"action-btn-middle\" style=\"color: #ffffff; font-weight: 700; text-decoration: none; font-size: 14px !important; padding-top:10px; padding-bottom:10px\" href=\""
				+ "http://localhost:8080/filedata2/user_recover.action?id="
				+ id
				+ "\" target=\"_blank\">点击这里重置密码</a>\n"
				+ "                                                            </td>\n"
				+ "\n"
				+ "                                                        </tr>\n"
				+ "                                                        </tbody>\n"
				+ "                                                    </table>\n"
				+ "                                                </td>\n"
				+ "                                            </tr>\n"
				+ "                                            </tbody>\n"
				+ "                                        </table>\n"
				+ "                                    </td>\n"
				+ "                                </tr>\n"
				+ "                                </tbody>\n"
				+ "                            </table>\n"
				+ "                        </td>\n"
				+ "                    </tr>\n"
				+ "\n"
				+ "                    <tr>\n"
				+ "                        <td border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"padding: 20px 0;\">\n"
				+ "                            <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" align=\"center\" style=\"color: #808080; font-size: 14px; line-height: 18px; border-collapse: collapse;\">\n"
				+ "\n"
				+ "                            </table>\n"
				+ "                            <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"border-collapse: collapse;\">\n"
				+ "                                <tbody>\n"
				+ "                                <tr>\n"
				+ "                                    <td class=\"unsubscribe\" width=\"100%\" style=\"padding: 20px\">\n"
				+ "                                        <div style=\"margin: 0; font-size: 11px; text-align: center; color: #BBBBBB;  -webkit-text-size-adjust:none;\">© 2017 Fileware</div>\n"
				+ "                                    </td>\n"
				+ "                                </tr>\n"
				+ "                                </tbody>\n"
				+ "                            </table>\n"
				+ "                        </td>\n"
				+ "                    </tr>\n"
				+ "                    </tbody>\n"
				+ "                </table>\n"
				+ "            </td>\n"
				+ "        </tr>\n"
				+ "        </tbody>\n"
				+ "    </table>\n"
				+ "    <br><br><div style=\"width:1px;height:0px;overflow:hidden\"></div>\n"
				+ "\n"
				+ "    <style type=\"text/css\">.qmbox style, .qmbox script, .qmbox head, .qmbox link, .qmbox meta {display: none !important;}</style></div></div><!-- --><style>#mailContentContainer .txt {height:auto;}</style>  </div>\n";

		return str;
	}

}
